version: '3.1'

services:

  db:
    image: postgres
    restart: always
    hostname: postgresDB
    container_name: postgresDB
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - iKnowNW

  pgdamin4:
    image: dpage/pgadmin4
    hostname: pgadmin4
    container_name: pgadmin4
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
    ports:
      - 8080:80
    networks:
      - iKnowNW

  php-fpm:
    build:
      context: ./php-fpm
      args:
          - PHP_VERSION=${PHP_VERSION}
          - XDEBUG_PORT=${XDEBUG_PORT}
    depends_on:
      - db
    environment:
      - XDEBUG_CONFIG=client_port=${XDEBUG_PORT}
    volumes:
      - ../src:/var/www
      - ./logs:/var/logs
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - iKnowNW

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - 8081:80
    networks:
      - iKnowNW

networks:
  iKnowNW:
      driver: bridge
